name: SAM Local Test

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install AWS SAM CLI
        run: |
          pip install --user pipx
          python -m pipx ensurepath
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          pipx install aws-sam-cli

      - name: Build SAM app using container
        run: |
          export SAM_CLI_TELEMETRY=0
          sam build --use-container

      - name: Start SAM API locally
        run: |
          nohup sam local start-api --port 3000 > sam.log 2>&1 &
          echo $! > pid.txt
          for i in {1..30}; do
            resp=$(curl -s http://127.0.0.1:3000/hello)
            [ -n "$resp" ] && break
            sleep 1
          done

      - name: Test endpoints
        run: |
          echo "GET /hello:"
          curl -s http://127.0.0.1:3000/hello

          echo "GET /hello?name=Raj:"
          curl -s "http://127.0.0.1:3000/hello?name=Raj"

      - name: Stop local API
        if: always()
        run: |
          [ -f pid.txt ] && kill $(cat pid.txt) || true
